# Create my-efs-pod.yaml file
apiVersion: v1
kind: Pod
metadata:
  name: my-efs-pod
spec:
  volumes:
  - name: efs-volume
    persistentVolumeClaim:
      claimName: efs-pvc  # The PVC that's backed by EFS
  containers:
  - name: my-container
    image: nginx:1.19  # Using a specific version for better reproducibility
    volumeMounts:
    - mountPath: /shared-data  # Path inside the container where the EFS volume will be mounted
      name: efs-volume